### PR TITLE
fix: Listview divider in leads tab

### PR DESCRIPTION
**Pull request by PareshMayani**
Listview divider was visible :)

screenshot_2015-07-25-23-28-58

### CODE REVIEW

**Comment by Splaktar** [comment]
Have an after screenshot? I assume the one above is before?

**Comment by tasomaniac** [comment]
What should we do with the the leads section title being two lines?

**Comment by PareshMayani** [comment]
@tasomaniac will fix it up and send it in a PR!

**Comment by tasomaniac** [comment]
@PareshMayani what is the suggested fix? It will be always 2 lines for small phones when we have 4 tabs.

**Comment by PareshMayani** [comment]
@tasomaniac I just created a separate issue #414, let's discuss there!

**Pull request merged**
