### PR TITLE
Refactor code into feature packages

### PR DESCRIPTION
**Pull request by HenriqueRocha**
On my flight from Berlin to Lisbon I did some cleanup to the code base.
A lot of commits even though it's just refactoring.
Feel free to read through the commit messages which are very self explanatory and very simple.

To summarize, I basically moved features to their own packages, hidden the visibility of certain classes where appropriate and fixed some lint issues.

### CODE REVIEW

**Comment by tasomaniac** [comment]
This is good but huge. I think we should merge it after we come back from Google I/O. Is it all refactoring or does it contain bug fixes too?

**Comment by HenriqueRocha** [comment]
No bug fixes, just refactoring. I can remove the commit that removes unused code and force push if you want.

**Comment by tasomaniac** [comment]
You can rebase and remove that commit if you want. I didn't review the whole PR. I can do it after I/O.

**Comment by HenriqueRocha** [comment]
@friedger Should I remove that "Remove unused stuff" commit?

**Comment by friedger** [comment]
I think we can merge it like it is.
Does the refactoring break anything? I mean have you thoroughly played with
the new build?
Am 22.05.2015 6:31 nachm. schrieb "Henrique Rocha" <notifications@github.com

**Comment by tasomaniac** [comment]
I've reviewed all of it. I think we should put back "Remove unused stuff" commit.

Otherwise, I added couple of small comments. We can discuss them real quick. 

And finally, most of the commits are really really related. I wish we could squash some of them.

**Comment by HenriqueRocha** [comment]
@tasomaniac Which commits should we actually squash? I find it easier to just leave it like this. But of course I can remove the "Remove stuff" commit. What's your opinion @friedger ?

**Comment by HenriqueRocha** [comment]
@tasomaniac @friedger This has been opened for a week now. How should we proceed on this? Merge it like this?

**Comment by friedger** [comment]
Could you revert the last commit?

**Comment by tasomaniac** [comment]
Squash'ing is absolutely not necessary and I know it will be hard. It was just a wish. :)

**Comment by tasomaniac** [comment]
+1 on @friedger 
I think we should merge asap w/o the last commit. I have couple of branches that I am working on. There will be lots of conflicts that I have to resolve. It is better to do them asap.

**Comment by tasomaniac** [comment]
Now I need to do rebasing. :)

**Pull request merged**
