### PR TITLE
Recents page above Lollipop is customized with a white logo.

### PR DESCRIPTION
**Pull request by tasomaniac**
Here is how it looks. No matter what is the primary color, it will look good. 

Before | After
----|----
shamulyz28etasomaniac08022015215222 | shamulyz28etasomaniac08022015215051

### CODE REVIEW

**Comment by fnk0** [comment]
It looks good to me! :octopus:  (I actually didn't knew that we could style those properties! Good to know!

**Comment by tasomaniac** [comment]
Yeah. Only color and logo. You cannot change the title color. It is created based on the background color.

**Comment by tasomaniac** [comment]
Thank you for the review.

**Comment by Splaktar** [comment]
Looks good. Would prefer to wait for 2.3.

**Comment by tasomaniac** [comment]
Sure.

**Comment by stefanhoth** [comment]
@tasomaniac I updated your description with a bit of markdown to make it easier to compare before/after. Hope you don't mind.

Template:
```
Before | After
----|----
![image before](http://somelong/url) | ![image after](http://somelong/otherurl)
```

**Comment by stefanhoth** [comment]
Nice improvement :+1:

**Comment by tasomaniac** [comment]
Of course I don't mind. Thank you. :smile:

**Comment by stefanhoth** [comment]
:ship: it!

**Pull request merged**
