### PR TITLE
Remove the profile picture if the user is not logged in anymore.

### LINKED ISSUE #406: on logout profile image in nav drawer should be removed.

### PR DESCRIPTION
**Pull request by tasomaniac**
Fixes #406

### CODE REVIEW

**Comment by friedger** [comment]
The navdrawer activity shouldn't be responsible for this in this explicit way. Couldn't we rely on the user being null?

**Comment by tasomaniac** [comment]
My fix is in NavDrawer Activity. 
The problem is that when the user logins, whe have `onConnected` callback. When the user logs out, there is no callback. So I am checking it in onResume.

**Comment by friedger** [comment]
This does not work if the user revokes rights in the Google console, doesn't it?

**Comment by tasomaniac** [comment]
Not sure. I don't think so. But I think that is out of this pr 's scope. We are saving the state in shared prefs. When user revokes it, we should delete our t data in shared prefs anyways.

**Comment by friedger** [comment]
Lgtm

**Pull request merged**
