### PR TITLE
Info Fragment

### PR DESCRIPTION
**Pull request by fnk0**
Fix for #269 

* Separated the cards for the fragment_info into it’s own separate files
* Modified the cards from fragment_info to follow the same design as
the cards in the GDE info fragment.

### Screenshots

portrait

landscape

### CODE REVIEW

**Comment by tasomaniac** [comment]
Do you think we should make the profile images circular? 
:)

**Comment by PareshMayani** [comment]
@tasomaniac yes rounded one would look better!

**Comment by fnk0** [comment]
@tasomaniac I'm always in favor of rounded images!! I'll do the change and push a commit in a little bit!

**Comment by tasomaniac** [comment]
Although @friedger s work contains this, I will merge this because it is small and nice improvement. 
Thank you for the contribution. 
@friedger you might have to rebase your branch. There will be conflicts.

**Pull request merged**
