### PR TITLE
Improvements on ArrowTaggedActivity

### PR DESCRIPTION
**Pull request by fnk0**
* Changed the ArrowTaggedActivity from ListView to RecyclerView
* Made the list items follow more of the design guidelines and changed cards to simple list items
* Fixed a bug that would keep making the list get populated if user hit home button and them came back to the app
* Reduced 1 layer of Overdraw by moving from CardView to a normal list
* Improved overall look of the list

#### Before (Cards with Overdraw)
before

#### After (List items without overdraw)
after

after_nogpu

### CODE REVIEW

**Comment by tasomaniac** [comment]
Why does Files Changed tab display 0 changes? :smile_cat:

**Comment by fnk0** [comment]
@tasomaniac I'm not sure. I committed to a wrong branch on my fork so I did a git reset -HEAD and committed it again to the right branch so I could do the PR. Something in there messed up that! I see that there's 2 commits with the same stuff. :sob:

**Comment by tasomaniac** [comment]
Somehow 2nd commit reverts the first commit and totally there are 0 changes.

**Comment by fnk0** [comment]
@tasomaniac I see! That's weeird!! I'm fixing that. I will probably just close this request and do a clean one with only 1 commit.

**Pull request closed without merging**
