### PR TITLE
use toolbar for EventActivity, use color references were possible

### PR DESCRIPTION
**Pull request by friedger**
Use a white text and blue popup as well

**Solution**
device-2015-03-01-233503

### CODE REVIEW

**Comment by friedger** [comment]
@HenriqueRocha I just realized now that I haven't assigned me to #261

**Comment by HenriqueRocha** [comment]
Why blue pop up? It's usually white with black text. If we do this here we would have to change it everywhere. Maybe we should post-pone changing the pop colour for now no?

**Comment by friedger** [comment]
I couldn't find any other overflow menu in the app. So this would be the
only plae


  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-03-01 23:43 GMT+01:00 Henrique Rocha <notifications@github.com>:

**Comment by HenriqueRocha** [comment]
:+1:

**Pull request merged**
