### PR TITLE
211/Use IO extended for special events

### PR DESCRIPTION
**Pull request by friedger**
This PR updates the details for the special events activity. It introduces an object for these details that can be updated in the future through the hub.

In addition, it moves the activity into its own package. It also fixes the SpecialEventActivity's use of end data extra.

### CODE REVIEW

**Comment by friedger** [comment]
use womentechmakers before io extended

**Comment by tasomaniac** [comment]
Why did you close this? I really liked the SpecialEvents class here. Can I use it and change it to wtm?

**Comment by friedger** [comment]
Yes, please do so. I just closed it because we want wt first.


  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-02-24 9:50 GMT+01:00 Said Tahsin Dane <notifications@github.com>:

**Comment by tasomaniac** [comment]
I wrote that comment before I saw your branch. That's why we had some
duplicate work but no problem.
You already merged mine. I will send another PR with multiple special event
series support.

**Pull request closed without merging**
