### PR TITLE
Update Copyright to 2015

### PR DESCRIPTION
**Pull request by HenriqueRocha**
Instead of removing the copyright from all the files as suggested in issue #182 I've done a "replace all" to change the copyright from 2013 to 2013-2015. Keeping the copyright in all the files doesn't seem that bad and it only requires one "replace all" and one commit per year to update.

### CODE REVIEW

**Comment by ViliusKraujutis** [comment]
:+1:

**Comment by ViliusKraujutis** [comment]
NB: includes couple import lines rearranges.

**Comment by HenriqueRocha** [comment]
Yes, I've noticed that also. Strange...

**Comment by ViliusKraujutis** [comment]
That's no problem. That's probably your IDE settings are to rearrange/optimize imports.

**Comment by HenriqueRocha** [comment]
I had those checkboxes unchecked. Maybe it was because I was working on the new pull to refresh and realized "Oh, I should update the copyright" and forgot to stash those changes.

**Comment by stefanhoth** [comment]
@HenriqueRocha As @friedger already mentioned the copyright and license info should be removed from all files rather than updated. We have the [LICENSE FILE](https://github.com/gdg-x/frisbee/blob/develop/LICENSE) to cover the whole project.

Or do I miss anything here?

**Comment by HenriqueRocha** [comment]
@stefanhoth As I commented in the first comment here, I proposed updating the copyright date of all files since it's one commit per year and then we keep the copyright in all the files.

The Apache Licence http://www.apache.org/dev/apply-license.html states the following:
Each original source document (code and documentation, but excluding the LICENSE and NOTICE files) SHOULD include a short license header at the top.

Since it doesn't say MUST, if you and @friedger consider that this PR is not relevant you can close it.

**Comment by friedger** [comment]
I am not an expert on licences, as the APL2 is very open anyway I don't think it matters a lot. I am happy with both solutions.

**Pull request merged**
