### PR TITLE
Feature/Add doorbell as in-app feedback provider

### PR DESCRIPTION
**Pull request by friedger**
This adds a simple alert dialog with a backend at https://doorbell.io/applications/917 (needs login details).
Doorbell could forward these to github issues or slack or more..

**Menu item**
device-2015-03-03-120936

**Menu item 2**
device-2015-03-03-120947

**Feedback dialog**
device-2015-03-03-121007

### CODE REVIEW

**Comment by tasomaniac** [comment]
Is it the default layout? Why is there nor padding in the dialog? Interesting. 
It looks good and it will be really good. 
Where should the button go? Help or about?

**Comment by friedger** [comment]
Currently, it is a menu, but we could add it in the nav drawer

**Comment by tasomaniac** [comment]
I think you also forget to add it to the menu. I've built your branch and couldn't see it.

**Comment by friedger** [comment]
@tasomaniac Sorry, I didn't commit any code. Need more sleep

**Comment by tasomaniac** [comment]
:smile:

**Comment by tasomaniac** [comment]
Funny: :smile: 
Doorbell requires a min SDK version of 3.

**Comment by friedger** [comment]
I think we should create our own client for their API. But that is another
PR.


  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-03-03 23:27 GMT+01:00 Said Tahsin Dane <notifications@github.com>:

**Comment by stefanhoth** [comment]
Could you add a bit of padding around the dialog? Or has this been addressed already?

**Comment by friedger** [comment]
this is part of the SDK, so not now currently

**Comment by tasomaniac** [comment]
screen shot 2015-03-04 at 01 12 16

**Comment by friedger** [comment]
but now it is fixed!

**Comment by stefanhoth** [comment]
That looks much nicer!

**Comment by stefanhoth** [comment]
Let's wait for the CI and go with it for now.

**Comment by friedger** [comment]
LGTM

**Comment by tasomaniac** [comment]
There is also a way to set email address and hide the second EditText for logged in users. 
After a login, why don't we store the email address of the user?

**Comment by friedger** [comment]
we ask for PLUS_LOGIN scope, handling/storing the email is a broader scope, hence I would avoid it for privacy reasons if not needed.

**Pull request merged**
