### PR TITLE
Some refactoring in the FirstStart* classes

### PR DESCRIPTION
**Pull request by HenriqueRocha**
While I was trying to figure out what was happening with the fact that chapters where not being fetched, I had my first exploration through the FirstStart* classes and thought I could do a bit of refactoring and code reformatting.

After talking to @stefanhoth he told me that the problem most probably was the fact that the SSL certificate had expired.

I thought it was okay to submit a pull request anyway with the changed I've made.

### CODE REVIEW

**Comment by stefanhoth** [comment]
@HenriqueRocha Thanks for the PR but the build failed with unknown classes. Can you check?

**Comment by HenriqueRocha** [comment]
@stefanhoth I believe it needs the changes that @tasomaniac did in his last PR which is not merged yet.

**Comment by stefanhoth** [comment]
Ok, I'll have a look!

Henrique Rocha schrieb:

**Comment by tasomaniac** [comment]
Sorry guys. My last pr was bad and Friedger merged it. My last pr is
successful. Even Travis builds are success now.

**Comment by stefanhoth** [comment]
Feel free to merge this one then as well if you reviewed it. 

On February 7, 2015 4:04:33 PM CET, Said Tahsin Dane <notifications@github.com> wrote:
>Sorry guys. My last pr was bad and Friedger merged it. My last pr is
>successful. Even Travis builds are success now.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gdg-x/frisbee/pull/178#issuecomment-73367698

--
Sent from mobile. Please excuse brevity and any typos.

**Pull request merged**
