### PR TITLE
Guard against NPE.

### PR DESCRIPTION
**Pull request by tasomaniac**
`isContextValid` is used to detect if the Fragment is still live after a network connection.

Fixes Crash 242
http://crashes.to/s/a08c9408cb3

### CODE REVIEW

**Comment by friedger** [comment]
Why have you removed the visibility change on success? If it fails in a first attempt?

**Comment by tasomaniac** [comment]
I don't think there is a point to make it INVISIBLE if it fails. Now it will just not load the image into ImageView which is very similat to making it INVISIBLE.

**Comment by tasomaniac** [comment]
If you don't like it, I can revert it. :smile:

**Comment by friedger** [comment]
The question is whether the fragment is reused. I don't know right now. When clicking through a tagged events list? Is it necessary to update the logo UI?

**Comment by tasomaniac** [comment]
This is used in every event detail. Both when the user is coming from Tagged event lists, or from the main page.

We are putting chapter logo for some reason. That page should be re designed anyways.

**Comment by friedger** [comment]
I meant reused without being recreated. Is it important that the UI is updated after it has been set at the first time.

**Comment by friedger** [comment]
:+1:

**Pull request merged**
