### PR TITLE
269/Add card style and use card style in fragments of main activity

### PR DESCRIPTION
**Pull request by friedger**
This PR adds a card style and uses it across fragments.

Before | After
---|----
isse 269|device-2015-07-26-145944

### CODE REVIEW

**Comment by PareshMayani** [comment]
Text and image inside card and header text are not aligned but it should be!

**Comment by PareshMayani** [comment]
I have already worked on this issue in past #313, are you still getting output same as depicted in "Before" screenshot?

**Comment by friedger** [comment]
"Before" is what it was before we started working on the whole thing :-)


  [image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2015-07-26 13:56 GMT+02:00 Paresh Mayani <notifications@github.com>:

**Comment by PareshMayani** [comment]
@friedger makes sense, but still contents in the card and header text should be aligned :)

**Comment by friedger** [comment]
@PareshMayani I was just to lazy to get a screenshot from before, sorry.

I have updated the PR with a new screenshot "After".

**Comment by PareshMayani** [comment]
@friedger cheers :+1:

**Comment by friedger** [comment]
continued in #416

**Pull request closed without merging**
