### PR TITLE
GoogleApiClient hopeful memory leak fix. 

### PR DESCRIPTION
**Pull request by tasomaniac**
Listeners are registered in onStart and unregistered in onStop

### CODE REVIEW

**Comment by stefanhoth** [comment]
I love the title.

**Comment by tasomaniac** [comment]
I will be honest. :) It actually doesn't fix. But it is an improvement.

**Comment by tasomaniac** [comment]
And I like the gif :)

**Comment by friedger** [comment]
I love the change, but don't have a gif ;-)

**Pull request merged**
