### PR TITLE
Library updates.

### PR DESCRIPTION
**Pull request by tasomaniac**
GMS is not updated to 8.1.0 because 8.1.0 has lots of problems,
Analytics makes the app larger, and apostate package seems to be empty.

and dex-count gradle plugin is added.

### CODE REVIEW

**Comment by friedger** [comment]
:+1:

**Comment by tasomaniac** [comment]
Damn we hit the dex limit again :cry: 
We are at 65765 currently. Just 200 extra methods.

Release build is around 23K. Damn huge libraries. What should we do? Enable multidex on debug builds? Remove couple of dependencies? Downgrade libraries?

**Comment by friedger** [comment]
Remove dependencies and build custom jars

**Comment by friedger** [comment]
As of today:

The following dependencies have later release versions:
 - com.android.support:appcompat-v7 [23.0.1 -> 23.1.1]
 - com.android.support:cardview-v7 [23.0.1 -> 23.1.1]
 - com.android.support:customtabs [23.0.1 -> 23.1.1]
 - com.android.support:design [23.0.1 -> 23.1.1]
 - com.android.support:recyclerview-v7 [23.0.1 -> 23.1.1]
 - com.android.support:support-annotations [23.0.1 -> 23.1.1]
 - com.android.support:support-v4 [23.0.1 -> 23.1.1]
 - com.android.support.test.espresso:espresso-core [2.2 -> 2.2.1]
 - com.android.tools.build:gradle [1.5.0 -> 2.0.0-alpha1]
 - com.crashlytics.sdk.android:crashlytics [2.5.2 -> 2.5.3]
 - com.github.triplet.gradle:play-publisher [1.1.3 -> 1.1.4]
 - com.google.android.gms:play-services-analytics [7.8.0 -> 8.3.0]
 - com.google.android.gms:play-services-appinvite [7.8.0 -> 8.3.0]
 - com.google.android.gms:play-services-appstate [7.8.0 -> 8.3.0]
 - com.google.android.gms:play-services-games [7.8.0 -> 8.3.0]
 - com.google.android.gms:play-services-gcm [7.8.0 -> 8.3.0]
 - com.google.android.gms:play-services-identity [7.8.0 -> 8.3.0]
 - com.google.android.gms:play-services-location [7.8.0 -> 8.3.0]
 - com.google.android.gms:play-services-plus [7.8.0 -> 8.3.0]
 - com.google.apis:google-api-services-plus [v1-rev126-1.18.0-rc -> v1-rev303-1.21.0]
 - com.google.code.findbugs:jsr305 [2.0.1 -> 3.0.1]
 - com.google.gms:google-services [1.4.0-beta1 -> 2.0.0-alpha1]
 - com.google.http-client:google-http-client-gson [1.20.0 -> 1.21.0]
 - com.jakewharton.timber:timber [3.1.0 -> 4.1.0]
 - com.squareup.okhttp:okhttp [2.5.0 -> 2.6.0]
 - com.squareup.okhttp:okhttp-urlconnection [2.5.0 -> 2.6.0]
 - com.squareup.retrofit:retrofit [1.9.0 -> 2.0.0-beta2]
 - net.danlew:android.joda [2.8.2 -> 2.9.0]
 - org.assertj:assertj-core [1.7.1 -> 3.2.0]
 - org.jsoup:jsoup [1.8.2 -> 1.8.3]

**Comment by friedger** [comment]
Closed until solution added

**Comment by tasomaniac** [comment]
Thank you for closing this. :) I think they improved the dex method count in 8.3 version of GMS. Lets try with the latest dependencies one more time.

**Pull request closed without merging**
