### PR TITLE
Retry button is added and duration is made infinite.

### PR DESCRIPTION
**Pull request by tasomaniac**
Here is how it looks. It is definitely out of guidelines. By default the Action color is the accent color. When we color the background, there is only little possibility that accent color will match with red, green, blue etc. So I made it all white for all cases. 

We definitely need a RETRY button there. We can do it like below. Or we can use the standard Snackbar. 

shamulyz28etasomaniac07222015134655

shamulyz28etasomaniac07222015135052

### CODE REVIEW

**Comment by PareshMayani** [comment]
Retry button is indeed required for this screen.

**Comment by Splaktar** [comment]
I prefer the standard snackbar. Making the retry text red or yellow may be appropriate in this case.

**Comment by tasomaniac** [comment]
I realized that they have color functions now. https://developer.android.com/sdk/support_api_diff/22.2.1/changes.html

**Comment by friedger** [comment]
LGTM

**Comment by tasomaniac** [comment]
Thank you for the merge. 
@Splaktar the theming of the Snackbar is I think out of this PR's scope. What do you think we should do? It is an easy task actually.

**Comment by Splaktar** [comment]
Yeah, it looks like we can use the default background for the snackbar and use Snackbar SetActionTextColor(ColorStateList) or Snackbar setActionTextColor(int) to set the `Retry` text color to red.

**Pull request merged**
