### PR TITLE
refactor: remove Google Developers Live classes

### PR DESCRIPTION
**Pull request by HenriqueRocha**
Like @mauimauer said before, GDL related classes should be removed. That's what this PR does.

### CODE REVIEW

**Comment by tasomaniac** [comment]
XML layouts and all related drawables should be removed as well.

**Comment by HenriqueRocha** [comment]
:x: I'm going to do what @tasomaniac said.

**Comment by HenriqueRocha** [comment]
Now it should be fine to merge. :+1:

**Comment by tasomaniac** [comment]
:+1:

**Pull request merged**
