### PR TITLE
373/Add TextInputLayout for AutoCompleteSpinner for power users when typing chapter name

### PR DESCRIPTION
**Pull request by friedger**
This PR adds a hint when the chapter name has been entered partly but only one chapter name matches the entered text.
device-sr

### CODE REVIEW

**Comment by tasomaniac** [comment]
TextInputLayout is good to show the hint while the user is typing. But I didn't understand why you added the chapter name into hint.

**Comment by friedger** [comment]
fixes #373

**Comment by friedger** [comment]
@tasomaniac You complained that the confirm button is enabled when the text is incomplete. The hint is now explaining why it is enabled.

**Comment by tasomaniac** [comment]
:smile: I actually didn't understand what it is doing :) I now understand it. It is really for power users. It becomes enabled and selects that 1 option.

**Comment by friedger** [comment]
the last commit was peer programmed with @tasomaniac

**Comment by tasomaniac** [comment]
I will merge this when the checks are successful.

**Comment by friedger** [comment]
Looks great!

**Pull request merged**
