### PR TITLE
Move LeadMessage class into the model package

### PR DESCRIPTION
**Pull request by PareshMayani**
LeadMessage class was in Lead package but it should be in model package. Moved it there.

### CODE REVIEW

**Comment by tasomaniac** [comment]
Henrique did it like that. Not only that but also other classes like that are in their own packages.

**Comment by PareshMayani** [comment]
I just found it and felt that it should be in model package so moved it. Hope I haven't made a mistake!

**Comment by tasomaniac** [comment]
I think it should be in the model package as well. But the thing is lots of
things are moved in Henrique s pr. And moving them again would not make
sense.

**Comment by PareshMayani** [comment]
@tasomaniac surprisingly it's not created/committed by Henrique but by Friedger :) 
lead folder history

**Comment by tasomaniac** [comment]
Oh ok. :smile:

**Pull request merged**
