### PR TITLE
MAINTAINERS file is added for lgtm.co support.

### PR DESCRIPTION
**Pull request by tasomaniac**

### CODE REVIEW

**Comment by friedger** [comment]
What is wrong here?

**Comment by tasomaniac** [comment]
Sorry forgot to mention that. I've enabled lgtm. Since this pr is not
merged yet it cannot know the maintainers. We should merge this without
looking at the lgtm check.

**Comment by tasomaniac** [comment]
I actually opened this PR as a question to you all :) I think it is really logical to have MAINTAINERS file. If you are not sure about it, we can close :)

**Comment by friedger** [comment]
An update to the README should be added as well.

**Pull request merged**
