### PR TITLE
Chore/Add help menu with link to google support

### PR DESCRIPTION
**Pull request by friedger**
This PR adds a help menu that links to the google support page for developer groups.

device-2015-02-24-222219

### CODE REVIEW

**Comment by tasomaniac** [comment]
Looks good

**Comment by HenriqueRocha** [comment]
LGTM :+1: 
I'll merge this once it goes green and rebase my new nav drawer code to solve the conflicts since `main_menu.xml` doesn't exist anymore because Settings and About should go to the navigation drawer and not the overflow menu.

**Comment by tasomaniac** [comment]
Lgtm to me too.

I would say if you are going to implement settings button in the navdrawer
add help too and don't merge this.

**Comment by HenriqueRocha** [comment]
@tasomaniac It's okay to merge this now. It's not that hard to solve the conflicts on this one. It will be a lot more work to solve the ones with the SpecialEvent thing because I've refactored a lot of code.

**Comment by tasomaniac** [comment]
I know. Let's talk about it tomorrow. Because I am going to continue to
work on that.

**Comment by HenriqueRocha** [comment]
I'll do my best to finish the new navigation drawer until Friday so that it can be reviewed during the weekend. There are a lot of changes so it will be a really big PR. Once everything is merged it will make all the Material stuff easier.

**Pull request merged**
