### PR TITLE
Redesign event details layout

### PR DESCRIPTION
**Pull request by PareshMayani**
Resolution for the https://github.com/gdg-x/frisbee/issues/270

screenshot_2015-03-21-02-44-30

### CODE REVIEW

**Comment by PareshMayani** [comment]
Thanks @friedger for accepting and merging.

**Comment by tasomaniac** [comment]
Me being a ninja. :) I think the texts should be aligned. Header and the card is aligned here. CardView is tricky.

**Comment by PareshMayani** [comment]
Texts are aligned on the left hand side. Header and card is not aligned, there is a difference of margin and padding. 
 
Please share more about the point if I haven't got it exactly.

**Comment by tasomaniac** [comment]
I think it is not important. There is a slight padding difference I think. At most 2dp. Nevermind :)

**Comment by friedger** [comment]
It matters. But this could be part of another PR.
Am 24.03.2015 08:51 schrieb "Said Tahsin Dane" <notifications@github.com>:

**Pull request merged**
